import { forwardRef, ButtonHTMLAttributes } from 'react';

// ─── Types ────────────────────────────────────────────────────────────────────
// Matches Prism DS Button component set (node: 361:3849) exactly:
//   Style:         Primary | Secondary | Subtle | Primary Destructive | Secondary Destructive | Warning
//   Size:          Large | Medium (Default) | Small | Tiny
//   Icon Position: None | Leading | Trailing | Icon Only
//   Inversed:      No | Yes
//   Floating:      No | Yes

export type ButtonStyle =
  | 'primary'
  | 'secondary'
  | 'subtle'
  | 'primary-destructive'
  | 'secondary-destructive'
  | 'warning';

export type ButtonSize = 'lg' | 'md' | 'sm' | 'tiny';
export type ButtonIconPosition = 'none' | 'leading' | 'trailing' | 'icon-only';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Maps to Figma Style property */
  variant?: ButtonStyle;
  /** Maps to Figma Size property */
  size?: ButtonSize;
  /** Maps to Figma Icon Position property */
  iconPosition?: ButtonIconPosition;
  /** Maps to Figma Inversed — use on dark/colored backgrounds */
  inversed?: boolean;
  /** Maps to Figma Floating — elevated shadow treatment */
  floating?: boolean;
  /** Loading state — shows spinner, disables interaction */
  loading?: boolean;
  /** Icon element for leading/trailing/icon-only positions */
  icon?: React.ReactNode;
  /** Expand button to fill container width */
  fullWidth?: boolean;
}

// ─── Style maps ───────────────────────────────────────────────────────────────
// Sourced from Figma node inspection of component set 361:3849.
// CSS vars are generated by scripts/build-tokens.js from tokens/colors.json.
//
// Measured fill/stroke/text values per style:
//   secondary fill:              #ffffff   → --color-primitive-neutral-default
//   secondary stroke:            #cccccc   → --color-primitive-neutral-gray-400
//   secondary + subtle text:     #1b1f22   → --color-primitive-neutral-gray-900
//   secondary font-weight:       450       → font-regular
//   primary fill:                #0084ff   → --color-primitive-brand-blue-500
//   primary/destructive/warning weight: 550 → font-semibold
//   primary-destructive fill:    #da3e37   → --color-primitive-error-red-500
//   warning fill:                #f58700   → --color-primitive-warning-orange-500
//   subtle:                      transparent fill, no stroke

const variantClasses: Record<ButtonStyle, string> = {
  primary: [
    'bg-[var(--color-primitive-brand-blue-500)] text-white font-semibold border-transparent',
    'hover:bg-[var(--color-primitive-brand-blue-600)]',
    'active:bg-[var(--color-primitive-brand-blue-700)]',
    'disabled:bg-[var(--color-primitive-neutral-gray-200)] disabled:text-[var(--color-primitive-neutral-gray-500)] disabled:cursor-not-allowed',
    'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primitive-brand-blue-500)]',
  ].join(' '),

  secondary: [
    'bg-[var(--color-primitive-neutral-default)] text-[var(--color-primitive-neutral-gray-900)] font-regular',
    'border border-[var(--color-primitive-neutral-gray-400)]',
    'hover:bg-[var(--color-primitive-neutral-gray-50)] hover:border-[var(--color-primitive-neutral-gray-500)]',
    'active:bg-[var(--color-primitive-neutral-gray-100)]',
    'disabled:bg-[var(--color-primitive-neutral-default)] disabled:text-[var(--color-primitive-neutral-gray-400)] disabled:border-[var(--color-primitive-neutral-gray-200)] disabled:cursor-not-allowed',
    'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primitive-brand-blue-500)]',
  ].join(' '),

  subtle: [
    'bg-transparent text-[var(--color-primitive-neutral-gray-900)] font-regular border-transparent',
    'hover:bg-[var(--color-primitive-neutral-gray-50)]',
    'active:bg-[var(--color-primitive-neutral-gray-100)]',
    'disabled:text-[var(--color-primitive-neutral-gray-400)] disabled:cursor-not-allowed',
    'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primitive-brand-blue-500)]',
  ].join(' '),

  'primary-destructive': [
    'bg-[var(--color-primitive-error-red-500)] text-white font-semibold border-transparent',
    'hover:bg-[var(--color-primitive-error-red-600)]',
    'active:bg-[var(--color-primitive-error-red-700)]',
    'disabled:bg-[var(--color-primitive-neutral-gray-200)] disabled:text-[var(--color-primitive-neutral-gray-500)] disabled:cursor-not-allowed',
    'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primitive-error-red-500)]',
  ].join(' '),

  'secondary-destructive': [
    'bg-[var(--color-primitive-neutral-default)] text-[var(--color-primitive-error-red-500)] font-regular',
    'border border-[var(--color-primitive-error-red-500)]',
    'hover:bg-[var(--color-primitive-error-red-50)]',
    'active:bg-[var(--color-primitive-error-red-100)]',
    'disabled:bg-[var(--color-primitive-neutral-default)] disabled:text-[var(--color-primitive-neutral-gray-400)] disabled:border-[var(--color-primitive-neutral-gray-200)] disabled:cursor-not-allowed',
    'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primitive-error-red-500)]',
  ].join(' '),

  warning: [
    'bg-[var(--color-primitive-warning-orange-500)] text-white font-semibold border-transparent',
    'hover:bg-[var(--color-primitive-warning-orange-600)]',
    'active:bg-[var(--color-primitive-warning-orange-700)]',
    'disabled:bg-[var(--color-primitive-neutral-gray-200)] disabled:text-[var(--color-primitive-neutral-gray-500)] disabled:cursor-not-allowed',
    'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primitive-warning-orange-500)]',
  ].join(' '),
};

// Sizes — from Figma node measurements:
//   Large:  height=36, paddingX=16, paddingY=8,  gap=6, radius=8
//   Medium: height=32, paddingX=12, paddingY=7,  gap=4, radius=8
//   Small:  height=28, paddingX=12, paddingY=5,  gap=4, radius=8
//   Tiny:   height=24, paddingX=12, paddingY=4,  gap=4, radius=6
const sizeClasses: Record<ButtonSize, string> = {
  lg:   'h-9  px-[var(--spacing-16)] gap-[var(--spacing-6)] text-body-md  rounded-[var(--radius-8)]',
  md:   'h-8  px-[var(--spacing-12)] gap-[var(--spacing-4)] text-body-md  rounded-[var(--radius-8)]',
  sm:   'h-7  px-[var(--spacing-12)] gap-[var(--spacing-4)] text-body-sm  rounded-[var(--radius-8)]',
  tiny: 'h-6  px-[var(--spacing-12)] gap-[var(--spacing-4)] text-caption-md rounded-[var(--radius-6)]',
};

const iconOnlySizeClasses: Record<ButtonSize, string> = {
  lg:   'h-9 w-9 p-0 rounded-[var(--radius-8)]',
  md:   'h-8 w-8 p-0 rounded-[var(--radius-8)]',
  sm:   'h-7 w-7 p-0 rounded-[var(--radius-8)]',
  tiny: 'h-6 w-6 p-0 rounded-[var(--radius-6)]',
};

// ─── Component ────────────────────────────────────────────────────────────────

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(({
  variant = 'primary',
  size = 'md',
  iconPosition = 'none',
  inversed = false,
  floating = false,
  loading = false,
  icon,
  fullWidth = false,
  disabled,
  children,
  className = '',
  ...props
}, ref) => {
  const isDisabled = disabled || loading;
  const isIconOnly = iconPosition === 'icon-only';

  return (
    <button
      ref={ref}
      disabled={isDisabled}
      aria-busy={loading}
      className={[
        'inline-flex items-center justify-center font-sans',
        'transition-colors duration-150 select-none whitespace-nowrap',
        variantClasses[variant],
        isIconOnly ? iconOnlySizeClasses[size] : sizeClasses[size],
        floating ? 'shadow-md' : '',
        inversed ? 'brightness-110' : '',
        fullWidth ? 'w-full' : '',
        className,
      ].filter(Boolean).join(' ')}
      {...props}
    >
      {loading && (
        <span
          aria-hidden="true"
          className="inline-block w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin shrink-0"
        />
      )}

      {!loading && (iconPosition === 'leading' || isIconOnly) && icon && (
        <span aria-hidden="true" className="shrink-0 flex items-center">
          {icon}
        </span>
      )}

      {!isIconOnly && children && (
        <span>{children}</span>
      )}

      {!loading && iconPosition === 'trailing' && icon && (
        <span aria-hidden="true" className="shrink-0 flex items-center">
          {icon}
        </span>
      )}
    </button>
  );
});

Button.displayName = 'Button';
export default Button;
