import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load tokens manually since we use a custom flat structure
const colors = JSON.parse(readFileSync(join(__dirname, '../tokens/colors.json'), 'utf8'));
const spacing = JSON.parse(readFileSync(join(__dirname, '../tokens/spacing.json'), 'utf8'));
const radius = JSON.parse(readFileSync(join(__dirname, '../tokens/radius.json'), 'utf8'));
const typography = JSON.parse(readFileSync(join(__dirname, '../tokens/typography.json'), 'utf8'));

// ─── Output CSS variables ──────────────────────────────────────────────────
function hexFromRgb(r, g, b) {
  const toHex = (v) => Math.round(v * 255).toString(16).padStart(2, '0');
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

function flattenColors(obj, prefix = '') {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}-${key}` : key;
    if (val && typeof val === 'object' && ('light' in val || 'dark' in val)) {
      result[fullKey] = val;
    } else if (val && typeof val === 'object') {
      Object.assign(result, flattenColors(val, fullKey));
    }
  }
  return result;
}

const flatColors = flattenColors(colors.color.primitive);
const flatSemantic = flattenColors(colors.color.semantic);

let cssLight = ':root {\n';
let cssDark = '[data-theme="dark"] {\n';

for (const [key, val] of Object.entries(flatColors)) {
  const varName = `--color-${key}`;
  cssLight += `  ${varName}: ${val.light};\n`;
  cssDark += `  ${varName}: ${val.dark};\n`;
}

// Spacing
for (const [key, val] of Object.entries(spacing.spacing)) {
  cssLight += `  --spacing-${key}: ${val.value};\n`;
}

// Radius
for (const [key, val] of Object.entries(radius.radius)) {
  cssLight += `  --radius-${key}: ${val.value};\n`;
}

// Typography
cssLight += `  --font-sans: ${typography.font.family.sans.value};\n`;
cssLight += `  --font-mono: ${typography.font.family.mono.value};\n`;

cssLight += '}\n\n';
cssDark += '}\n';

mkdirSync(join(__dirname, '../src'), { recursive: true });
writeFileSync(join(__dirname, '../src/tokens.css'), cssLight + cssDark);
console.log('✅ Generated src/tokens.css');

// ─── Output tailwind.config.ts ────────────────────────────────────────────
const spacingEntries = Object.keys(spacing.spacing)
  .filter(k => !k.startsWith('-'))
  .map(k => `    '${k}': 'var(--spacing-${k})'`)
  .join(',\n');

const radiusEntries = Object.entries(radius.radius)
  .map(([k, v]) => `    '${k}': 'var(--radius-${k})'`)
  .join(',\n');

const colorEntries = Object.keys(flatColors)
  .map(k => `    '${k}': 'var(--color-${k})'`)
  .join(',\n');

const tailwindConfig = `import type { Config } from 'tailwindcss';

// Generated by scripts/build-tokens.js — do not edit manually.
// Source of truth: tokens/*.json

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    // Desktop-first breakpoints (nav states handled via CSS vars/context)
    // Mobile breakpoints to be added in a future migration pass.
    screens: {
      'md': { 'max': '1920px' },
      'lg': { 'min': '1921px' },
    },
    extend: {
      colors: {
${colorEntries}
      },
      spacing: {
${spacingEntries}
      },
      borderRadius: {
${radiusEntries}
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Roboto Mono', 'monospace'],
      },
      fontSize: {
        'h1':         ['32px', { lineHeight: '40px' }],
        'h2':         ['24px', { lineHeight: '30px' }],
        'h3':         ['20px', { lineHeight: '25px' }],
        'body-lg':    ['16px', { lineHeight: '20px' }],
        'body-md':    ['14px', { lineHeight: '18px' }],
        'body-sm':    ['13px', { lineHeight: '16px' }],
        'caption-md': ['12px', { lineHeight: '15px' }],
        'caption-sm': ['10px', { lineHeight: '12px' }],
      },
      fontWeight: {
        bold:     '650',
        semibold: '550',
        medium:   '550',
        regular:  '450',
      },
    },
  },
  plugins: [],
};

export default config;
`;

writeFileSync(join(__dirname, '../tailwind.config.ts'), tailwindConfig);
console.log('✅ Generated tailwind.config.ts');
